---

- name: reload rethinkdb
  become: yes
  become_method: sudo
  service: name=rethinkdb state=reloaded

- name: restart rethinkdb
  become: yes
  become_method: sudo
  service: name=rethinkdb state=restarted
